//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeForDotNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeForDotNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronous operation attempted to complete twice..
        /// </summary>
        internal static string AsyncCompleteCalledTwice {
            get {
                return ResourceManager.GetString("AsyncCompleteCalledTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronous operation already ended..
        /// </summary>
        internal static string AsyncEndCalledTwice {
            get {
                return ResourceManager.GetString("AsyncEndCalledTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale is only valid for Texture brush types..
        /// </summary>
        internal static string BrushScaleOnlyForTextures {
            get {
                return ResourceManager.GetString("BrushScaleOnlyForTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single color brushes do not have an angle..
        /// </summary>
        internal static string BrushSingleColorHasNoAngle {
            get {
                return ResourceManager.GetString("BrushSingleColorHasNoAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textures do not have a color setting..
        /// </summary>
        internal static string BrushTextureHasNoColor {
            get {
                return ResourceManager.GetString("BrushTextureHasNoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextureWrapMode property is only valid for Textures!.
        /// </summary>
        internal static string BrushTextureWrapModeOnlyForTextures {
            get {
                return ResourceManager.GetString("BrushTextureWrapModeOnlyForTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current brush type does not have an End color..
        /// </summary>
        internal static string BrushTypeHasNoEndColor {
            get {
                return ResourceManager.GetString("BrushTypeHasNoEndColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current brush type does not have a texture..
        /// </summary>
        internal static string BrushTypeHasNoTexture {
            get {
                return ResourceManager.GetString("BrushTypeHasNoTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating or opending registry key &quot;{0}&quot;..
        /// </summary>
        internal static string CreateOpenRegistryKeyError {
            get {
                return ResourceManager.GetString("CreateOpenRegistryKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change properties of a data object when it&apos;s current state is deleted..
        /// </summary>
        internal static string DataObjectChangePropertyStateInvalid {
            get {
                return ResourceManager.GetString("DataObjectChangePropertyStateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a data object when it&apos;s current state indicates it exists or is pending deletion..
        /// </summary>
        internal static string DataObjectCreateStateInvalid {
            get {
                return ResourceManager.GetString("DataObjectCreateStateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a data object when it&apos;s current state is not current or changed..
        /// </summary>
        internal static string DataObjectDeleteStateInvalid {
            get {
                return ResourceManager.GetString("DataObjectDeleteStateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read a data object when it&apos;s current state is deleted..
        /// </summary>
        internal static string DataObjectReadStateInvalid {
            get {
                return ResourceManager.GetString("DataObjectReadStateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update a data object when it&apos;s current state is not changed..
        /// </summary>
        internal static string DataObjectUpdateStateInvalid {
            get {
                return ResourceManager.GetString("DataObjectUpdateStateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string DaysOfWeekFriday {
            get {
                return ResourceManager.GetString("DaysOfWeekFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string DaysOfWeekMonday {
            get {
                return ResourceManager.GetString("DaysOfWeekMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string DaysOfWeekSaturday {
            get {
                return ResourceManager.GetString("DaysOfWeekSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string DaysOfWeekSunday {
            get {
                return ResourceManager.GetString("DaysOfWeekSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string DaysOfWeekThursday {
            get {
                return ResourceManager.GetString("DaysOfWeekThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string DaysOfWeekTuesday {
            get {
                return ResourceManager.GetString("DaysOfWeekTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string DaysOfWeekWednesday {
            get {
                return ResourceManager.GetString("DaysOfWeekWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse source string to DxDy! Should be #;# format..
        /// </summary>
        internal static string DxDyStringInvalid {
            get {
                return ResourceManager.GetString("DxDyStringInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying directory {0}....
        /// </summary>
        internal static string FileExtensionsCopyDirectoryCreateDirectory {
            get {
                return ResourceManager.GetString("FileExtensionsCopyDirectoryCreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file {0}....
        /// </summary>
        internal static string FileExtensionsCopyDirectoryFile {
            get {
                return ResourceManager.GetString("FileExtensionsCopyDirectoryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert &quot;{0}&quot; to a signed number of base {1}..
        /// </summary>
        internal static string NumberParseFormatErrorSigned {
            get {
                return ResourceManager.GetString("NumberParseFormatErrorSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert &quot;{0}&quot; to an unsigned number of base {1}..
        /// </summary>
        internal static string NumberParseFormatErrorUnsigned {
            get {
                return ResourceManager.GetString("NumberParseFormatErrorUnsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;{0}&quot; is required..
        /// </summary>
        internal static string PropertyRequired {
            get {
                return ResourceManager.GetString("PropertyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} instance(s); {1}.
        /// </summary>
        internal static string ScheduleItemCollectionToStringFormat {
            get {
                return ResourceManager.GetString("ScheduleItemCollectionToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string ScheduleItemCollectionToStringSeparator {
            get {
                return ResourceManager.GetString("ScheduleItemCollectionToStringSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        internal static string ScheduleItemOffsetFirst {
            get {
                return ResourceManager.GetString("ScheduleItemOffsetFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        internal static string ScheduleItemOffsetLast {
            get {
                return ResourceManager.GetString("ScheduleItemOffsetLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string ScheduleItemOffsetSecond {
            get {
                return ResourceManager.GetString("ScheduleItemOffsetSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third.
        /// </summary>
        internal static string ScheduleItemOffsetThird {
            get {
                return ResourceManager.GetString("ScheduleItemOffsetThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {3} day(s) starting on {0:d} at {0:t} for {2} minute(s) until {4} occurrences ({1:d} at {1:t}).
        /// </summary>
        internal static string ScheduleItemToStringDailyFixedEnd {
            get {
                return ResourceManager.GetString("ScheduleItemToStringDailyFixedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {3} day(s) starting on {0:d} at {0:t} for {2} minutes.
        /// </summary>
        internal static string ScheduleItemToStringDailyNoEnd {
            get {
                return ResourceManager.GetString("ScheduleItemToStringDailyNoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or .
        /// </summary>
        internal static string ScheduleItemToStringDayOfWeekSeparator {
            get {
                return ResourceManager.GetString("ScheduleItemToStringDayOfWeekSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {3} hour(s) starting on {0:d} at {0:t} for {2} minute(s) until {4} occurrences ({1:d} at {1:t}).
        /// </summary>
        internal static string ScheduleItemToStringHourlyFixedEnd {
            get {
                return ResourceManager.GetString("ScheduleItemToStringHourlyFixedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {3} hour(s) starting on {0:d} at {0:t} for {2} minute(s).
        /// </summary>
        internal static string ScheduleItemToStringHourlyNoEnd {
            get {
                return ResourceManager.GetString("ScheduleItemToStringHourlyNoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {3} month(s) starting on {0:d} at {0:t} for {2} minute(s) until {4} occurrences ({1:d} at {1:t}).
        /// </summary>
        internal static string ScheduleItemToStringMonthlyDayFixedEnd {
            get {
                return ResourceManager.GetString("ScheduleItemToStringMonthlyDayFixedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {3} month(s) starting on {0:d} at {0:t} for {2} minute(s).
        /// </summary>
        internal static string ScheduleItemToStringMonthlyDayNoEnd {
            get {
                return ResourceManager.GetString("ScheduleItemToStringMonthlyDayNoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {4} month(s) on the {3} {0:dddd} starting on {0:d} at {0:t} for {2} minute(s).
        /// </summary>
        internal static string ScheduleItemToStringMonthlyOffsetNoEnd {
            get {
                return ResourceManager.GetString("ScheduleItemToStringMonthlyOffsetNoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {4} month(s) on the {3} {0:dddd} starting on {0:d} at {0:t} for {2} minute(s) until {5} occurrences ({1:d} at {1:t}).
        /// </summary>
        internal static string ScheduleItemToStringMonthlyOffsetRecurring {
            get {
                return ResourceManager.GetString("ScheduleItemToStringMonthlyOffsetRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to once on {0:d} at {0:t} for {1} minute(s).
        /// </summary>
        internal static string ScheduleItemToStringOnce {
            get {
                return ResourceManager.GetString("ScheduleItemToStringOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {4} week(s) on {3} starting on {0:d} at {0:t} for {2} minute(s) until {5} occurrences ({1:d} at {1:t}).
        /// </summary>
        internal static string ScheduleItemToStringWeeklyFixedEnd {
            get {
                return ResourceManager.GetString("ScheduleItemToStringWeeklyFixedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {4} week(s) on {3} starting on {0:d} at {0:t} for {2} minute(s).
        /// </summary>
        internal static string ScheduleItemToStringWeeklyNoEnd {
            get {
                return ResourceManager.GetString("ScheduleItemToStringWeeklyNoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {3} year(s) starting on {0:d} at {0:t} for {2} minute(s) until {4} occurrences ({1:d} at {1:t}).
        /// </summary>
        internal static string ScheduleItemToStringYearlyDayFixedEnd {
            get {
                return ResourceManager.GetString("ScheduleItemToStringYearlyDayFixedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {3} year(s) starting on {0:d} at {0:t} for {2} minute(s).
        /// </summary>
        internal static string ScheduleItemToStringYearlyDayNoEnd {
            get {
                return ResourceManager.GetString("ScheduleItemToStringYearlyDayNoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {4} year(s) on the {3} {0:dddd} starting on {0:d} at {0:t} for {2} minute(s) until {5} occurrences ({1:d} at {1:t}).
        /// </summary>
        internal static string ScheduleItemToStringYearlyOffsetFixedEnd {
            get {
                return ResourceManager.GetString("ScheduleItemToStringYearlyOffsetFixedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {4} year(s) on the {3} {0:dddd} starting on {0:d} at {0:t} for {2} minute(s).
        /// </summary>
        internal static string ScheduleItemToStringYearlyOffsetNoEnd {
            get {
                return ResourceManager.GetString("ScheduleItemToStringYearlyOffsetNoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes {0}. Excludes {1}..
        /// </summary>
        internal static string ScheduleToStringFormatIncludesAndExcludes {
            get {
                return ResourceManager.GetString("ScheduleToStringFormatIncludesAndExcludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes {0}..
        /// </summary>
        internal static string ScheduleToStringFormatIncludesOnly {
            get {
                return ResourceManager.GetString("ScheduleToStringFormatIncludesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never..
        /// </summary>
        internal static string ScheduleToStringFormatNone {
            get {
                return ResourceManager.GetString("ScheduleToStringFormatNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML validation error at line {0} character {1}. {2}.
        /// </summary>
        internal static string XmlValdiationError {
            get {
                return ResourceManager.GetString("XmlValdiationError", resourceCulture);
            }
        }
    }
}
