using System.Diagnostics;

namespace CodeForDotNet.Diagnostics
{
    /// <summary>
    /// Holds information generated by running a <see cref="Process"/>.
    /// </summary>
    public class ProcessResult
    {
        /// <summary>
        /// Return code, when the process exited normally.
        /// </summary>
        public int? ReturnCode { get; set; }

        /// <summary>
        /// Console standard output (if any).
        /// </summary>
        /// <remarks>
        /// Windowed applications will normally have no console output.
        /// </remarks>
        public string Output { get; set; }

        /// <summary>
        /// Console error output (if any).
        /// </summary>
        /// <remarks>
        /// Windowed applications will normally have no console output.
        /// </remarks>
        public string Errors { get; set; }

        /// <summary>
        /// Indicates the process timed-out,
        /// in which case the <see cref="ReturnCode"/> is null.
        /// </summary>
        public bool TimedOut { get; set; }
    }
}
