//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeForDotNet.Tests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TestFormatXmlInputFilePath {
            get {
                return ((string)(this["TestFormatXmlInputFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TestFormatXmlOutputIndentTrimFilePath {
            get {
                return ((string)(this["TestFormatXmlOutputIndentTrimFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TestFormatXmlOutputIndentOmitCommentsTrimFilePath {
            get {
                return ((string)(this["TestFormatXmlOutputIndentOmitCommentsTrimFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TestFormatXmlOutputIndentOmitCommentsFilePath {
            get {
                return ((string)(this["TestFormatXmlOutputIndentOmitCommentsFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TestFormatXmlOutputIndentFilePath {
            get {
                return ((string)(this["TestFormatXmlOutputIndentFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TestFormatXmlOutputTrimUtf16FilePath {
            get {
                return ((string)(this["TestFormatXmlOutputTrimUtf16FilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TestFormatXmlInputFragmentFilePath {
            get {
                return ((string)(this["TestFormatXmlInputFragmentFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TestFormatXmlOutputFragmentFilePath {
            get {
                return ((string)(this["TestFormatXmlOutputFragmentFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TestXmlValidationSchemaFilePath {
            get {
                return ((string)(this["TestXmlValidationSchemaFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TestXPathFunctionsInputFilePath {
            get {
                return ((string)(this["TestXPathFunctionsInputFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TestXPathFunctionsExecuteFilePath {
            get {
                return ((string)(this["TestXPathFunctionsExecuteFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TestXPathFunctionsOutputFilePath {
            get {
                return ((string)(this["TestXPathFunctionsOutputFilePath"]));
            }
        }
    }
}
