//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeForDotNet.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeForDotNet.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM Application Name {0} was not found after installation..
        /// </summary>
        internal static string ErrorComPlusApplicationNameUnconfirmed {
            get {
                return ResourceManager.GetString("ErrorComPlusApplicationNameUnconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a unique {0}.ConditionArgument, it is required to store uninstall information in the saved state..
        /// </summary>
        internal static string ErrorMissingConditionProperty {
            get {
                return ResourceManager.GetString("ErrorMissingConditionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;{0}&quot; is required..
        /// </summary>
        internal static string PropertyRequired {
            get {
                return ResourceManager.GetString("PropertyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing changes....
        /// </summary>
        internal static string StatusCommtitingChanges {
            get {
                return ResourceManager.GetString("StatusCommtitingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring COM+ application {0}....
        /// </summary>
        internal static string StatusConfigureComPlusApplication {
            get {
                return ResourceManager.GetString("StatusConfigureComPlusApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted service..
        /// </summary>
        internal static string StatusDeletedService {
            get {
                return ResourceManager.GetString("StatusDeletedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file {0}.
        /// </summary>
        internal static string StatusDeletingFile {
            get {
                return ResourceManager.GetString("StatusDeletingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lnstalling component {0} into the GAC....
        /// </summary>
        internal static string StatusGacInstallComponent {
            get {
                return ResourceManager.GetString("StatusGacInstallComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lnstalling dependency {0} into the GAC....
        /// </summary>
        internal static string StatusGaclnstallDependency {
            get {
                return ResourceManager.GetString("StatusGaclnstallDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing component {0} from the GAC....
        /// </summary>
        internal static string StatusGacRemoveComponent {
            get {
                return ResourceManager.GetString("StatusGacRemoveComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing dependency {0} from the GAC....
        /// </summary>
        internal static string StatusGacRemoveDependency {
            get {
                return ResourceManager.GetString("StatusGacRemoveDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} installer performing install action for condition {1}....
        /// </summary>
        internal static string StatusInstall {
            get {
                return ResourceManager.GetString("StatusInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file {0}.
        /// </summary>
        internal static string StatusLoadingFile {
            get {
                return ResourceManager.GetString("StatusLoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating local .NET application config to COM manifest (application.manifest and application.config)....
        /// </summary>
        internal static string StatusMigratingDotNetConfigToLocalManifest {
            get {
                return ResourceManager.GetString("StatusMigratingDotNetConfigToLocalManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering COM+ component {0}....
        /// </summary>
        internal static string StatusRegisterComPlusComponent {
            get {
                return ResourceManager.GetString("StatusRegisterComPlusComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing COM+application {0}....
        /// </summary>
        internal static string StatusRemovingComPlusApplication {
            get {
                return ResourceManager.GetString("StatusRemovingComPlusApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing COM+ application {0} instance {1}....
        /// </summary>
        internal static string StatusRemovingComPlusApplicationInstance {
            get {
                return ResourceManager.GetString("StatusRemovingComPlusApplicationInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down services....
        /// </summary>
        internal static string StatusShutdownServices {
            get {
                return ResourceManager.GetString("StatusShutdownServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping missing file {0}.
        /// </summary>
        internal static string StatusSkippingMissingFile {
            get {
                return ResourceManager.GetString("StatusSkippingMissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} installer performing uninstall action for condition {1}....
        /// </summary>
        internal static string StatusUninstall {
            get {
                return ResourceManager.GetString("StatusUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistering COM+ component {0}....
        /// </summary>
        internal static string StatusUnregisterComPlusComponent {
            get {
                return ResourceManager.GetString("StatusUnregisterComPlusComponent", resourceCulture);
            }
        }
    }
}
